name: party-mode
description: "Multi-agent collaboration mode for complex Shape Up tasks requiring multiple perspectives"
author: "ECM"

config_source: "{project-root}/_ecm/core/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"

installed_path: "{project-root}/_ecm/core/workflows/party-mode"
instructions: "{installed_path}/instructions.md"

available_agents:
  - shaper
  - pitcher
  - technical-shaper
  - cycle-lead
  - builder
